# Generated by Django 5.0.3 on 2024-04-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestor', '0002_fornecedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=12)),
                ('codigo_barras', models.IntegerField(max_length=12)),
                ('nome_produto', models.CharField(max_length=40)),
                ('ref', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=15)),
                ('categoria', models.CharField(max_length=10)),
                ('preco_compra', models.FloatField(max_length=8)),
                ('localizacao', models.CharField(max_length=3)),
                ('fornecedor', models.CharField(max_length=40)),
                ('data_entrada', models.DateField()),
                ('validade', models.DateField()),
            ],
        ),
    ]
