# Generated by Django 5.0.3 on 2024-04-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestor', '0004_produtos_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='codigo_barras',
            field=models.IntegerField(),
        ),
    ]
