# Generated by Django 5.0.3 on 2024-06-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestor', '0007_alter_produtos_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='quantidade_alerta',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestor.fornecedores'),
        ),
    ]
