# Generated by Django 5.0.3 on 2024-06-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestor', '0008_alter_produtos_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='quantidade_alerta',
            field=models.IntegerField(default=1),
        ),
    ]
